name: CI Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3

    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pandas sqlalchemy kaggle pytest

    
    - name: Configure Kaggle API credentials
      run: |
        mkdir -p ~/.kaggle
        echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

    
    - name: Create database and tables
      run: |
        sqlite3 data/train_data.sqlite <<EOF
        CREATE TABLE IF NOT EXISTS cost_of_living (
            household_id BIGINT,
            housing_expenses FLOAT,
            food_expenses FLOAT,
            transport_expenses FLOAT,
            healthcare_expenses FLOAT,
            other_necessities_expenses FLOAT,
            childcare_expenses FLOAT,
            household_taxes FLOAT,
            total_household_expenses FLOAT,
            parents_per_household INTEGER,
            children_per_household INTEGER,
            state TEXT
        );

        CREATE TABLE IF NOT EXISTS house_listings (
            property_price FLOAT,
            property_area_meters FLOAT,
            price_per_sq_meter FLOAT,
            state TEXT
        );
        EOF

    
    - name: Run tests
      run: |
        chmod +x ./project/tests.sh
        ./project/tests.sh
